### ISSUE TITLE
changed group_membership but it still looking for a table group_membership

### ISSUE THREAD

**Issue by kainio** [dwbutler/groupify#66]
When i do
 User.as(:admin)
knowing that I changed the group_membership to organization_membership in the initializer 
I got
  User Load (1.0ms)  SELECT  `users`.* FROM `users` INNER JOIN `organization_memberships` ON `organization_memberships`.`member_id` = `users`.`id` AND `organization_memberships`.`member_type` = 'User' WHERE `group_memberships`.`membership_type` = 'admin' LIMIT 11
ActiveRecord::StatementInvalid: Mysql2::Error: Unknown column 'group_memberships.membership_type' in 'where clause': SELECT  `users`.* FROM `users` INNER JOIN `organization_memberships` ON `organization_memberships`.`member_id` = `users`.`id` AND `organization_memberships`.`member_type` = 'User' WHERE `group_memberships`.`membership_type` = 'admin' LIMIT 11
Why it's still looking for group_memberships table ?

**Comment by dwbutler** [comment]
This was fixed in https://github.com/dwbutler/groupify/pull/64 but hasn't been released yet.

**Comment by kainio** [comment]
I am using now the latest version of groupify repo in my gemfile and it's working fine, but named groups are still not working.

**Comment by joelvh** [comment]
@kainio major refactor in #61 - would you be willing to test that out?
